// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYYt3aVHG7DOLGgCgJulxugwI8XLB2SFw',
    appId: '1:1028780277592:web:c3a2fac1d2736287d36f2d',
    messagingSenderId: '1028780277592',
    projectId: 'signinsignuptestapp',
    authDomain: 'signinsignuptestapp.firebaseapp.com',
    storageBucket: 'signinsignuptestapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgiHbz6JNxBCiXadYlo9iPV5tPbY00hU',
    appId: '1:1028780277592:android:3142555632c4d2dad36f2d',
    messagingSenderId: '1028780277592',
    projectId: 'signinsignuptestapp',
    storageBucket: 'signinsignuptestapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlkwSFD2XKXZXdvMj0oXgGAnmjgInbcc4',
    appId: '1:1028780277592:ios:a9f333219d56abfcd36f2d',
    messagingSenderId: '1028780277592',
    projectId: 'signinsignuptestapp',
    storageBucket: 'signinsignuptestapp.appspot.com',
    iosBundleId: 'com.example.signinSighnup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlkwSFD2XKXZXdvMj0oXgGAnmjgInbcc4',
    appId: '1:1028780277592:ios:1e8dde46c71f5dccd36f2d',
    messagingSenderId: '1028780277592',
    projectId: 'signinsignuptestapp',
    storageBucket: 'signinsignuptestapp.appspot.com',
    iosBundleId: 'com.example.signinSighnup.RunnerTests',
  );
}
